### ISSUE TITLE
Why 2,3,4 etc Rooms, make minimum 5

### ISSUE THREAD

**Issue by binayakranjan** [kushal-r/MyWorkspace#1]
https://github.com/kushal-r/MyWorkspace/blob/6cbcef8722c91b8b4e41f5b430616a75041cc690/SystemDesign/MeetingRoomBookingSystem/src/com/systemdesign/constants/RoomCapacity.java#L11

**Comment by kushal-r** [comment]
Meeting rooms can have any capacity from 2onwards we can simple add entry in the roomcapacity enum to hold future req.
